export default {
  privacy: {
    title: "Privacy policy",
    intro:
      "Last updated: 9 Dec 2025. The website www.redblue.sk is operated by RedBlue Solutions s. r. o., Company ID: 55522467, Tax ID: 2122005897, registered office: Sadová 2719/3A, 905 01 Senica, Slovakia (the \"controller\"). We process personal data in line with Regulation (EU) 2016/679 (GDPR) and Slovak Act No. 18/2018 on personal data protection. This policy explains which personal data we process, why we process it, on what legal basis, and what rights you have.",
    sections: [
      {
        heading: "Service operator",
        paragraphs: [
          "RedBlue Solutions s. r. o., Company ID: 55522467, Tax ID: 2122005897",
          "Registered office: Sadová 2719/3A, 905 01 Senica, Slovakia",
          "Email: info@redblueacademy.com",
          "The site www.redblue.sk is a marketing presentation of services and projects of RedBlue Solutions s. r. o.",
        ],
      },
      {
        heading: "Data we process (contact form)",
        paragraphs: [
          "If you contact us via the website, we may process: name and surname (if provided), email address, phone number (if provided), city or organization (if provided), message content.",
          "Legal basis: Art. 6(1)(b) GDPR – pre-contractual steps / handling your request; or Art. 6(1)(f) GDPR – legitimate interest where it is not a direct service request.",
        ],
      },
      {
        heading: "Automatically processed technical data",
        paragraphs: [
          "When you view our site, technical data may be recorded: IP address and time of visit, device and browser type. These data are processed by the hosting provider solely to protect the server and prevent attacks. The controller does not actively store or further use these data.",
          "Legal basis: Art. 6(1)(f) GDPR – legitimate interest in securing the website.",
        ],
      },
      {
        heading: "Cookies",
        paragraphs: [
          "The site does not use analytics, marketing, or personalization cookies. Only technical cookies generated by the browser/hosting are used, for basic site operation and secure access to content. These cookies do not identify the visitor and are not used for marketing or traffic measurement.",
        ],
        links: [
          {
            label: "See detailed cookie policy",
            href: "/cookies",
          },
        ],
      },
      {
        heading: "Purpose of processing personal data",
        paragraphs: [
          "We process your personal data only for: replying to your message; potential conclusion of a service agreement; follow-up communication to start cooperation; keeping communication records in case of a complaint or legitimate claim. We do not use the data for other purposes and do not perform automated profiling.",
        ],
      },
      {
        heading: "Retention period",
        paragraphs: [
          "We keep your data for up to 6 months from the last communication if no cooperation starts. If a business relationship arises, we keep the data for the duration of the service and subsequently for 10 years if required by law (e.g., accounting). After the retention period, data are securely deleted.",
        ],
      },
      {
        heading: "Sharing with third parties",
        paragraphs: [
          "We do not share personal data with third parties except the web hosting provider (Hostinger International Ltd.) and legally required situations (e.g., enforcement proceedings, public authorities). We never sell data, transfer it for marketing, or provide it outside the EU other than in line with GDPR.",
        ],
      },
      {
        heading: "Your rights",
        paragraphs: [
          "You have the right to: ask for confirmation whether we process your data; access your data; request rectification; request erasure; restrict processing; object to processing based on legitimate interest; request data portability; withdraw consent if given. You can exercise your rights by contacting info@redblueacademy.com.",
        ],
      },
      {
        heading: "Security of processing",
        paragraphs: [
          "Your personal data are protected by technical and organizational measures preventing unauthorized access, leakage, or misuse. We process data only to the extent necessary for the given purpose. No internet transmission can be guaranteed 100% secure, but we adhere to appropriate security standards.",
        ],
      },
      {
        heading: "Final provisions and supervisory authority",
        paragraphs: [
          "These principles may be updated due to legislative changes or website operations. The current version is always available at www.redblue.sk.",
          "You have the right to lodge a complaint with the supervisory authority: Office for Personal Data Protection of the Slovak Republic, Hraničná 12, 820 07 Bratislava, www.dataprotection.gov.sk.",
        ],
      },
    ],
    contact: {
      heading: "Contact information",
      paragraphs: [
        "If you want to reach us about this policy or to exercise your rights, email:",
      ],
      email: "info@redblueacademy.com",
    },
  },
};
